import type { TemplateItem } from "@/lib/content/types"

export const templates: TemplateItem[] = [
  {
    id: "income-statement",
    title: "Income Statement Template",
    description: "Professional P&L template with revenue categories, COGS, and expense tracking.",
    icon: "FileText",
    price: "Free",
    tier: "free",
    status: "coming-soon",
    notes: "No spreadsheet is attached yet. The listing stays in the catalog so the ID remains stable. Coming Soon — no download and no checkout.",
    features: ["Revenue & expense categories", "Gross profit calculation", "Net income summary", "Monthly comparison columns", "Year-to-date totals"],
  },
  {
    id: "balance-sheet",
    title: "Balance Sheet Template",
    description: "Track assets, liabilities, and equity with this clean, professional balance sheet.",
    icon: "FileSpreadsheet",
    price: "Free",
    tier: "free",
    status: "coming-soon",
    notes: "No file is available. Coming Soon. You can still follow the Bookkeeping Basics lessons to sketch a balance sheet by hand.",
    features: ["Asset categorization", "Liability tracking", "Equity section", "Auto-calculating totals", "Monthly comparison"],
  },
  {
    id: "cash-flow",
    title: "Cash Flow Statement Template",
    description: "Understand where your cash is coming from and going to. Operating, investing, and financing sections.",
    icon: "DollarSign",
    price: "Free",
    tier: "free",
    status: "coming-soon",
    notes: "The worksheet is not ready for download. Coming Soon. The cash-flow course explains the three sections in writing.",
    features: ["Operating activities", "Investing activities", "Financing activities", "Net cash change", "Beginning & ending balance"],
  },
  {
    id: "invoice-pro",
    title: "Professional Invoice Pack",
    description: "5 invoice templates for different billing scenarios. Hourly, project, retainer, and more.",
    icon: "Receipt",
    price: "$19",
    tier: "pro",
    status: "coming-soon",
    notes: "No pack is for sale on this page. Checkout is not enabled. The $19 figure is the existing catalog price, not a live charge.",
    features: ["Hourly & project invoices", "Retainer billing template", "Late payment tracking", "Professional branding", "Editable DOCX format"],
  },
  {
    id: "tax-worksheet",
    title: "Tax Deduction Worksheet",
    description: "Comprehensive deduction tracker. Categorize and document every write-off throughout the year.",
    icon: "Calculator",
    price: "$15",
    tier: "pro",
    status: "coming-soon",
    notes: "No worksheet file and no payment form. Coming Soon. Use a dated folder of receipts until a file ships.",
    features: ["All Schedule C categories", "Receipt tracker with notes", "Mileage log with rates", "Home office calculator", "Year-end summary report"],
  },
  {
    id: "payroll-sheets",
    title: "Payroll Register Template",
    description: "Track employee pay, withholdings, and employer taxes. Perfect for small teams.",
    icon: "Users",
    price: "$19",
    tier: "pro",
    status: "coming-soon",
    notes: "No register file is available. Coming Soon. A payroll service register is the usual source of truth for a first employee.",
    features: ["Employee pay tracking", "Tax withholding calculator", "Employer tax tracking", "Pay period summaries", "Year-end W-2 reconciliation"],
  },
  {
    id: "budget-template",
    title: "Business Budget Planner",
    description: "Plan and track your business budget with monthly projections and actuals comparison.",
    icon: "FileSpreadsheet",
    price: "$12",
    tier: "pro",
    status: "coming-soon",
    notes: "No planner file. Coming Soon. The cash-flow course covers a 13-week forecast you can build in any spreadsheet.",
    features: ["Revenue projections", "Expense categories", "Actual vs budget tracking", "Variance analysis", "Annual summary"],
  },
  {
    id: "chart-of-accounts",
    title: "Chart of Accounts Guide",
    description: "Pre-built chart of accounts for 10 common business types. Customize and import into any accounting software.",
    icon: "FileText",
    price: "$9",
    tier: "pro",
    status: "coming-soon",
    notes: "No import file. Coming Soon. Lesson 2 of Bookkeeping Basics explains how to write a short chart yourself.",
    features: ["10 industry-specific COAs", "Account numbering system", "Standard categories", "QuickBooks/Xero ready", "Customization guide"],
  },
]

export function getTemplate(id: string): TemplateItem | undefined {
  return templates.find((template) => template.id === id)
}
